[build]
  publish = "out"
  command = "npm run build-prod"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# a8 = 2.5.8
# a9 = 2.6.1
# a10 = 3.1.3

[[redirects]]
  from = "/qr/a8"
  to = "/docs/v2.6.1"
  status = 302
  force = false

[[redirects]]
  from = "/qr/a9"
  to = "/docs/v2.6.1"
  status = 302
  force = false

[[redirects]]
  from = "/qr/a10"
  to = "/docs"
  status = 302
  force = false
